# Generated by Django 3.2.9 on 2023-10-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BimAtend',
            fields=[
                ('corp_no', models.IntegerField(db_column='CORP_NO', primary_key=True, serialize=False)),
                ('labortime_type', models.CharField(db_column='LABORTIME_TYPE', max_length=6)),
                ('labor_time_nm', models.CharField(blank=True, db_column='LABOR_TIME_NM', max_length=30, null=True)),
                ('st_time', models.CharField(blank=True, db_column='ST_TIME', max_length=10, null=True)),
                ('end_time', models.CharField(blank=True, db_column='END_TIME', max_length=10, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=1, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('reg_id', models.CharField(blank=True, db_column='REG_ID', max_length=15, null=True)),
                ('upt_dtime', models.DateTimeField(blank=True, db_column='UPT_DTIME', null=True)),
                ('upt_id', models.CharField(blank=True, db_column='UPT_ID', max_length=15, null=True)),
            ],
            options={
                'db_table': 'BIM_ATEND',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BimDept',
            fields=[
                ('corp_no', models.IntegerField(db_column='CORP_NO', primary_key=True, serialize=False)),
                ('dept_no', models.CharField(db_column='DEPT_NO', max_length=6)),
                ('dept_nm', models.CharField(blank=True, db_column='DEPT_NM', max_length=30, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=1, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('reg_id', models.CharField(blank=True, db_column='REG_ID', max_length=15, null=True)),
                ('upt_dtime', models.DateTimeField(blank=True, db_column='UPT_DTIME', null=True)),
                ('upt_id', models.CharField(blank=True, db_column='UPT_ID', max_length=15, null=True)),
            ],
            options={
                'db_table': 'BIM_DEPT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BimHday',
            fields=[
                ('corp_no', models.IntegerField(db_column='CORP_NO', primary_key=True, serialize=False)),
                ('std_year', models.CharField(db_column='STD_YEAR', max_length=4)),
                ('hday_date', models.CharField(db_column='HDAY_DATE', max_length=4)),
                ('hday_nm', models.CharField(blank=True, db_column='HDAY_NM', max_length=50, null=True)),
                ('type', models.CharField(blank=True, db_column='TYPE', max_length=1, null=True)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=200, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('reg_id', models.CharField(blank=True, db_column='REG_ID', max_length=15, null=True)),
                ('upt_dtime', models.DateTimeField(blank=True, db_column='UPT_DTIME', null=True)),
                ('upt_id', models.CharField(blank=True, db_column='UPT_ID', max_length=15, null=True)),
            ],
            options={
                'db_table': 'BIM_HDAY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BimOfcps',
            fields=[
                ('corp_no', models.IntegerField(db_column='CORP_NO', primary_key=True, serialize=False)),
                ('ofcps', models.CharField(db_column='OFCPS', max_length=6)),
                ('ofcps_nm', models.CharField(blank=True, db_column='OFCPS_NM', max_length=30, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=1, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('reg_id', models.CharField(blank=True, db_column='REG_ID', max_length=15, null=True)),
                ('upt_dtime', models.DateTimeField(blank=True, db_column='UPT_DTIME', null=True)),
                ('upt_id', models.CharField(blank=True, db_column='UPT_ID', max_length=15, null=True)),
            ],
            options={
                'db_table': 'BIM_OFCPS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BimSalary',
            fields=[
                ('corp_no', models.IntegerField(db_column='CORP_NO', primary_key=True, serialize=False)),
                ('salary_item', models.CharField(db_column='SALARY_ITEM', max_length=6)),
                ('salary_type', models.CharField(db_column='SALARY_TYPE', max_length=1)),
                ('item_nm', models.CharField(blank=True, db_column='ITEM_NM', max_length=30, null=True)),
                ('taxt_yn', models.CharField(blank=True, db_column='TAXT_YN', max_length=1, null=True)),
                ('trmmg_unit', models.CharField(blank=True, db_column='TRMMG_UNIT', max_length=1, null=True)),
                ('use_yn', models.CharField(blank=True, db_column='USE_YN', max_length=1, null=True)),
                ('std_info_val', models.CharField(blank=True, db_column='STD_INFO_VAL', max_length=4, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('reg_id', models.CharField(blank=True, db_column='REG_ID', max_length=15, null=True)),
                ('upt_dtime', models.DateTimeField(blank=True, db_column='UPT_DTIME', null=True)),
                ('upt_id', models.CharField(blank=True, db_column='UPT_ID', max_length=15, null=True)),
            ],
            options={
                'db_table': 'BIM_SALARY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmmCode',
            fields=[
                ('lcode', models.CharField(db_column='LCODE', max_length=4, primary_key=True, serialize=False)),
                ('scode', models.CharField(db_column='SCODE', max_length=6)),
                ('cd_val', models.CharField(blank=True, db_column='CD_VAL', max_length=250, null=True)),
                ('seq', models.IntegerField(blank=True, db_column='SEQ', null=True)),
                ('desc', models.CharField(blank=True, db_column='DESC', max_length=4000, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('reg_id', models.CharField(blank=True, db_column='REG_ID', max_length=15, null=True)),
                ('upt_dtime', models.DateTimeField(blank=True, db_column='UPT_DTIME', null=True)),
                ('upt_id', models.CharField(blank=True, db_column='UPT_ID', max_length=15, null=True)),
            ],
            options={
                'db_table': 'CMM_CODE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComAtendlst',
            fields=[
                ('grp_no', models.IntegerField(db_column='GRP_NO', primary_key=True, serialize=False)),
                ('lcode', models.CharField(db_column='LCODE', max_length=4)),
                ('scode', models.CharField(db_column='SCODE', max_length=6)),
                ('st_time', models.CharField(blank=True, db_column='ST_TIME', max_length=10, null=True)),
                ('end_time', models.CharField(blank=True, db_column='END_TIME', max_length=10, null=True)),
            ],
            options={
                'db_table': 'COM_ATENDLST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComGrpinfo',
            fields=[
                ('grp_no', models.IntegerField(db_column='GRP_NO', primary_key=True, serialize=False)),
                ('grp_type', models.CharField(blank=True, db_column='GRP_TYPE', max_length=1, null=True)),
                ('grp_nm', models.CharField(blank=True, db_column='GRP_NM', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=1, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('reg_id', models.CharField(blank=True, db_column='REG_ID', max_length=15, null=True)),
                ('upt_dtime', models.DateTimeField(blank=True, db_column='UPT_DTIME', null=True)),
                ('upt_id', models.CharField(blank=True, db_column='UPT_ID', max_length=15, null=True)),
            ],
            options={
                'db_table': 'COM_GRPINFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComHday',
            fields=[
                ('std_year', models.CharField(db_column='STD_YEAR', max_length=4, primary_key=True, serialize=False)),
                ('hday_date', models.CharField(db_column='HDAY_DATE', max_length=4)),
                ('hday_nm', models.CharField(blank=True, db_column='HDAY_NM', max_length=50, null=True)),
                ('type', models.CharField(blank=True, db_column='TYPE', max_length=1, null=True)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=200, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('applc_dtime', models.DateTimeField(blank=True, db_column='APPLC_DTIME', null=True)),
            ],
            options={
                'db_table': 'COM_HDAY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComIcmtaxrt',
            fields=[
                ('std_year', models.CharField(db_column='STD_YEAR', max_length=4, primary_key=True, serialize=False)),
                ('taxt_std_lwlt', models.DecimalField(db_column='TAXT_STD_LWLT', decimal_places=0, max_digits=13)),
                ('taxt_std_uplt', models.DecimalField(db_column='TAXT_STD_UPLT', decimal_places=0, max_digits=13)),
                ('taxrt', models.DecimalField(blank=True, db_column='TAXRT', decimal_places=3, max_digits=5, null=True)),
                ('dedn_amt', models.DecimalField(blank=True, db_column='DEDN_AMT', decimal_places=0, max_digits=13, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('applc_dtime', models.DateTimeField(blank=True, db_column='APPLC_DTIME', null=True)),
            ],
            options={
                'db_table': 'COM_ICMTAXRT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComInsrncrate',
            fields=[
                ('std_date', models.DateField(db_column='STD_DATE', primary_key=True, serialize=False)),
                ('irncf_type', models.CharField(db_column='IRNCF_TYPE', max_length=2)),
                ('insrnc_rate', models.DecimalField(blank=True, db_column='INSRNC_RATE', decimal_places=3, max_digits=5, null=True)),
                ('lwstlmt_amt', models.DecimalField(blank=True, db_column='LWSTLMT_AMT', decimal_places=0, max_digits=13, null=True)),
                ('toplmt_amt', models.DecimalField(blank=True, db_column='TOPLMT_AMT', decimal_places=0, max_digits=13, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=1, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('applc_dtime', models.DateTimeField(blank=True, db_column='APPLC_DTIME', null=True)),
            ],
            options={
                'db_table': 'COM_INSRNCRATE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComOgdplst',
            fields=[
                ('grp_no', models.IntegerField(db_column='GRP_NO', primary_key=True, serialize=False)),
                ('lcode', models.CharField(db_column='LCODE', max_length=4)),
                ('scode', models.CharField(db_column='SCODE', max_length=6)),
            ],
            options={
                'db_table': 'COM_OGDPLST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComSalarylst',
            fields=[
                ('grp_no', models.IntegerField(db_column='GRP_NO', primary_key=True, serialize=False)),
                ('lcode', models.CharField(db_column='LCODE', max_length=4)),
                ('scode', models.CharField(db_column='SCODE', max_length=6)),
                ('salary_type', models.CharField(blank=True, db_column='SALARY_TYPE', max_length=1, null=True)),
                ('item_nm', models.CharField(blank=True, db_column='ITEM_NM', max_length=30, null=True)),
                ('taxt_yn', models.CharField(blank=True, db_column='TAXT_YN', max_length=1, null=True)),
                ('trmmg_unit', models.CharField(blank=True, db_column='TRMMG_UNIT', max_length=1, null=True)),
                ('use_yn', models.CharField(blank=True, db_column='USE_YN', max_length=1, null=True)),
                ('std_info_val', models.CharField(blank=True, db_column='STD_INFO_VAL', max_length=4, null=True)),
            ],
            options={
                'db_table': 'COM_SALARYLST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComSmpltax',
            fields=[
                ('std_year', models.CharField(db_column='STD_YEAR', max_length=4, primary_key=True, serialize=False)),
                ('salary_above', models.DecimalField(db_column='SALARY_ABOVE', decimal_places=0, max_digits=13)),
                ('salary_belo', models.DecimalField(db_column='SALARY_BELO', decimal_places=0, max_digits=13)),
                ('fmly_num_1', models.IntegerField(blank=True, db_column='FMLY_NUM_1', null=True)),
                ('fmly_num_2', models.IntegerField(blank=True, db_column='FMLY_NUM_2', null=True)),
                ('fmly_num_3', models.IntegerField(blank=True, db_column='FMLY_NUM_3', null=True)),
                ('fmly_num_4', models.IntegerField(blank=True, db_column='FMLY_NUM_4', null=True)),
                ('fmly_num_5', models.IntegerField(blank=True, db_column='FMLY_NUM_5', null=True)),
                ('fmly_num_6', models.IntegerField(blank=True, db_column='FMLY_NUM_6', null=True)),
                ('fmly_num_7', models.IntegerField(blank=True, db_column='FMLY_NUM_7', null=True)),
                ('fmly_num_8', models.IntegerField(blank=True, db_column='FMLY_NUM_8', null=True)),
                ('fmly_num_9', models.IntegerField(blank=True, db_column='FMLY_NUM_9', null=True)),
                ('fmly_num_10', models.IntegerField(blank=True, db_column='FMLY_NUM_10', null=True)),
                ('fmly_num_11', models.IntegerField(blank=True, db_column='FMLY_NUM_11', null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, db_column='REG_DTIME', null=True)),
                ('applc_dtime', models.DateTimeField(db_column='APPLC_DTIME')),
            ],
            options={
                'db_table': 'COM_SMPLTAX',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HtmEmplphoto',
            fields=[
                ('photo_id', models.IntegerField(db_column='PHOTO_ID', primary_key=True, serialize=False)),
                ('file_org_nm', models.CharField(blank=True, db_column='FILE_ORG_NM', max_length=50, null=True)),
                ('file_modify_nm', models.CharField(blank=True, db_column='FILE_MODIFY_NM', max_length=50, null=True)),
                ('file_path', models.CharField(blank=True, db_column='FILE_PATH', max_length=200, null=True)),
                ('file_size', models.IntegerField(blank=True, db_column='FILE_SIZE', null=True)),
                ('crt_dtime', models.DateTimeField(blank=True, db_column='CRT_DTIME', null=True)),
                ('upt_dtime', models.DateTimeField(blank=True, db_column='UPT_DTIME', null=True)),
            ],
            options={
                'db_table': 'HTM_EMPLPHOTO',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='atmhday',
            name='corp_no',
        ),
        migrations.RemoveField(
            model_name='atmhdaybase',
            name='corp_no',
        ),
        migrations.RemoveField(
            model_name='atmlabortime',
            name='corp_no',
        ),
        migrations.RemoveField(
            model_name='cmmscode',
            name='lcode',
        ),
        migrations.RemoveField(
            model_name='hrmdept',
            name='corp_no',
        ),
        migrations.RemoveField(
            model_name='slminsrncrate',
            name='corp_no',
        ),
        migrations.RemoveField(
            model_name='slmitemcd',
            name='corp_no',
        ),
        migrations.DeleteModel(
            name='AtmCrtlwh',
        ),
        migrations.DeleteModel(
            name='AtmHday',
        ),
        migrations.DeleteModel(
            name='AtmHdaybase',
        ),
        migrations.DeleteModel(
            name='AtmLabortime',
        ),
        migrations.DeleteModel(
            name='CmmLcode',
        ),
        migrations.DeleteModel(
            name='CmmScode',
        ),
        migrations.DeleteModel(
            name='HrmDept',
        ),
        migrations.DeleteModel(
            name='SlmInsrncrate',
        ),
        migrations.DeleteModel(
            name='SlmItemcd',
        ),
    ]
